# Generated by Django 5.0.4 on 2024-04-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorizador', '0002_sensor_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='timestamp',
            field=models.DateTimeField(default='14.04.2024T18:00:32.883383'),
        ),
    ]
