# Generated by Django 5.0.4 on 2024-04-14 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorizador', '0004_alter_sensor_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='timestamp',
            field=models.TimeField(default=datetime.datetime(2024, 4, 14, 18, 5, 52, 393558)),
        ),
    ]
