# Generated by Django 5.0.4 on 2024-04-14 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorizador', '0005_alter_sensor_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 14, 18, 7, 52, 839635)),
        ),
    ]
