# Generated by Django 5.0.4 on 2024-04-15 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorizador', '0007_alter_sensor_equipmentid_alter_sensor_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 15, 14, 11, 34, 95720, tzinfo=datetime.timezone.utc)),
        ),
    ]
